const state={sections:new Map(),active:null,questions:[],questionIndex:0,score:0};
const $=s=>document.querySelector(s);const folderInput=$('#folderInput');const toast=$('#toast');
const showToast=message=>{toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000)};
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function sectionFor(path){const parts=path.split('/');return parts.length>1?parts[parts.length-2]:'Unsorted notes'}
function addFiles(files){const pdfs=[...files].filter(f=>f.type==='application/pdf'||f.name.toLowerCase().endsWith('.pdf'));if(!pdfs.length){showToast('No PDF files found in that folder.');return}pdfs.forEach(file=>{const name=sectionFor(file.webkitRelativePath||file.name);if(!state.sections.has(name))state.sections.set(name,[]);state.sections.get(name).push({file,name:file.name,url:URL.createObjectURL(file),text:''})});renderNav();$('#welcome').classList.add('hidden');$('#reader').classList.remove('hidden');const first=[...state.sections.values()][0][0];selectFile(first,nameOfSection(first));showToast(`${pdfs.length} PDF${pdfs.length>1?'s':''} indexed locally`)}
function nameOfSection(item){for(const [key,files] of state.sections)if(files.includes(item))return key;return 'Notes'}
function renderNav(){const nav=$('#sectionNav');nav.innerHTML='';let total=0;state.sections.forEach((files,section)=>{total+=files.length;const wrap=document.createElement('div');wrap.className='nav-section';wrap.innerHTML=`<div class="nav-section-label">${escapeHtml(section)}</div>`;files.forEach(item=>{const button=document.createElement('button');button.className='nav-item';button.dataset.id=item.url;button.innerHTML=`<span>◻</span><span title="${escapeHtml(item.name)}">${escapeHtml(item.name.replace(/\.pdf$/i,''))}</span>`;button.onclick=()=>selectFile(item,section);wrap.append(button)});nav.append(wrap)});$('#fileCount').textContent=total;$('#sectionCount').textContent=state.sections.size}
async function extractText(file){if(file.text)return file.text;try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const data=await file.file.arrayBuffer();const pdf=await pdfjs.getDocument({data}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,40);i++){const page=await pdf.getPage(i);const content=await page.getTextContent();text+=' '+content.items.map(x=>x.str).join(' ')}file.text=text.replace(/\s+/g,' ').trim();return file.text}catch(e){return ''}}
async function selectFile(item,section){state.active=item;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.id===item.url));$('#sectionLabel').textContent=section.toUpperCase();$('#fileTitle').textContent=item.name;$('#pdfFrame').src=item.url;$('#pdfPlaceholder').style.display='none';$('#pageMeta').textContent=`${section.toUpperCase()}  /  PDF READER`;$('#progressMeta').textContent='Fresh questions on every open';resetQuiz();extractText(item)}
function resetQuiz(){state.questions=[];state.questionIndex=0;state.score=0;$('#quizPanel').classList.remove('quiz-playing');$('#quizPanel').innerHTML='<div class="quiz-intro"><span class="quiz-spark">✦</span><p class="eyebrow">ACTIVE RECALL</p><h3>Ready when<br>you are.</h3><p>Open a quiz for this PDF. Ten questions will be freshly generated from its content every time.</p><button class="primary full" id="startQuiz">Start challenge <span>→</span></button></div>';$('#startQuiz').onclick=startQuiz}
function sentences(text){return (text||'').match(/[^.!?]+[.!?]+/g)?.map(s=>s.trim()).filter(s=>s.length>45&&s.length<260)||[]}
function makeQuestions(text){const ss=sentences(text);if(ss.length<3)return [];const pool=shuffle(ss);const words=[...new Set(text.split(/\W+/).filter(w=>w.length>5))];return Array.from({length:Math.min(10,pool.length)},(_,i)=>{const source=pool[i];const target=source.split(/\s+/).filter(w=>w.length>6)[Math.floor(Math.random()*Math.max(1,source.split(/\s+/).filter(w=>w.length>6).length))]||source.split(/\s+/)[2];const blank=source.replace(new RegExp(`\\b${target}\\b`,'i'),'_____');const wrong=shuffle(words.filter(w=>w.toLowerCase()!==target.toLowerCase()&&w.length>4)).slice(0,3);return {q:`Which term best completes this statement from the notes? “${blank}”`,correct:target,answers:shuffle([target,...wrong])}})}
async function startQuiz(){const text=await extractText(state.active);state.questions=makeQuestions(text);if(!state.questions.length){showToast('This PDF has no extractable text for quiz generation.');return}state.questionIndex=0;state.score=0;$('#quizPanel').classList.add('quiz-playing');renderQuestion()}
function renderQuestion(){const q=state.questions[state.questionIndex];$('#quizPanel').innerHTML=`<div class="quiz-intro"><div class="quiz-number">QUESTION ${state.questionIndex+1} / ${state.questions.length}</div><p class="quiz-question">${escapeHtml(q.q)}</p><div class="answers">${q.answers.map(a=>`<button class="answer" data-answer="${escapeHtml(a)}">${escapeHtml(a)}</button>`).join('')}</div><button class="primary quiz-next" style="display:none">Continue <span>→</span></button></div>`;document.querySelectorAll('.answer').forEach(btn=>btn.onclick=()=>answer(btn,q));}
function answer(button,q){if(document.querySelector('.answer.correct,.answer.wrong'))return;const right=button.dataset.answer===q.correct;button.classList.add(right?'correct':'wrong');if(right)state.score++;else document.querySelector(`[data-answer="${CSS.escape(q.correct)}"]`)?.classList.add('correct');const next=$('.quiz-next');next.style.display='block';next.onclick=()=>{state.questionIndex++;state.questionIndex<state.questions.length?renderQuestion():renderResult()}}
function renderResult(){$('#quizPanel').innerHTML=`<div class="quiz-intro quiz-result"><span class="quiz-spark">✦</span><p class="eyebrow">CHALLENGE COMPLETE</p><strong>${state.score}/${state.questions.length}</strong><h3>Knowledge, retained.</h3><p>That set was generated from this PDF just now. Open it again or retry for a completely new challenge.</p><button class="primary full" id="retry">Try a new set <span>↻</span></button></div>`;$('#retry').onclick=startQuiz}
folderInput.onchange=e=>addFiles(e.target.files);$('#addButton').onclick=()=>folderInput.click();$('#welcomeAdd').onclick=()=>folderInput.click();$('#quizButton').onclick=startQuiz;$('#startQuiz').onclick=startQuiz;$('#openButton').onclick=()=>state.active&&window.open(state.active.url,'_blank');
const drop=$('#dropzone');['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>addFiles(e.dataTransfer.files));$('#themeToggle').onclick=()=>document.body.classList.toggle('high-contrast');document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();folderInput.click()}});
